name: Varo
version: "1.0"
main: de.tzimom.siro.Main
description: Main plugin for a varo project
author: Tzimom
authors:
  - xQuiesel

commands:
  team:
    usage: /team create <TeamName> [<PlayerName> ...]
    description: Creates a new team
#  time:
#    usage: /time
#    description: Displays the time left to play on the server that day