name: Siro
version: "1.0"
main: de.tzimom.siro.Main
description: Main plugin for a siro project
author: Tzimom
authors:
  - xQuiesel

commands:
  team:
    usage: /team create <TeamName> <PlayerName1> [<PlayerName2>]
    description: Creates a new team
  siro:
    usage: /siro [start]|[stop]|[
    description: Starts the game
  time:
    usage: /time
    description: Displays the time left to play on the server that day